// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsal8L742RlUQgfxwLWjTVAasw8uCFbuU',
    appId: '1:821542283157:android:9efbc47735c8cd6320789c',
    messagingSenderId: '821542283157',
    projectId: 'furnday-15bd6',
    storageBucket: 'furnday-15bd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIn1ljS0GsErsiC_GAIV1o2mW9aCnX7uk',
    appId: '1:821542283157:ios:ae8fd2770d7b56ab20789c',
    messagingSenderId: '821542283157',
    projectId: 'furnday-15bd6',
    storageBucket: 'furnday-15bd6.appspot.com',
    androidClientId: '821542283157-4upjkpfbfjgachvvacerbdmkvt9319od.apps.googleusercontent.com',
    iosClientId: '821542283157-vn1o28dq35bin591fu8uk9nllam4d57n.apps.googleusercontent.com',
    iosBundleId: 'com.furnday.furndayseller.furndayseller',
  );
}
